#!/usr/bin/env python3
"""
sanity_check_pysat.py

This script performs the final sanity check (your idea 7.C).
It runs a classical PySAT solver directly on the two CNF benchmark
files to confirm their true satisfiability status.

This will definitively resolve the contradiction we see in the 'uf20-01' results.
"""

import time
from pysat.solvers import Glucose3
from pysat.formula import CNF

# --- Paste the exact CNF content from qlto_fpt_solver_v4.py ---

# uf20-01.cnf
UF20_01_CNF_CONTENT = """c This Formular is generated by mcnf
c
c    horn? no 
c    forced? no 
c    mixed sat? no 
c    clause length = 3 
c
p cnf 20  91 
 4 -18 19 0
3 18 -5 0
-5 -8 -15 0
-20 7 -16 0
10 -13 -7 0
-12 -9 17 0
17 19 5 0
-16 9 15 0
11 -5 -14 0
18 -10 13 0
-3 11 12 0
-6 -17 -8 0
-18 14 1 0
-19 -15 10 0
12 18 -19 0
-8 4 7 0
-8 -9 4 0
7 17 -15 0
12 -7 -14 0
-10 -11 8 0
2 -15 -11 0
9 6 1 0
-11 20 -17 0
9 -15 13 0
12 -7 -17 0
-18 -2 20 0
20 12 4 0
19 11 14 0
-16 18 -4 0
-1 -17 -19 0
-13 15 10 0
-12 -14 -13 0
12 -14 -7 0
-7 16 10 0
6 10 7 0
20 14 -16 0
-19 17 11 0
-7 1 -20 0
-5 12 15 0
-4 -9 -13 0
12 -11 -7 0
-5 19 -8 0
1 16 17 0
20 -14 -15 0
13 -4 10 0
14 7 10 0
-5 9 20 0
10 1 -19 0
-16 -15 -1 0
16 3 -11 0
-15 -10 4 0
4 -15 -3 0
-10 -16 11 0
-8 12 -5 0
14 -6 12 0
1 6 11 0
-13 -5 -1 0
-7 -2 12 0
1 -20 19 0
-2 -13 -8 0
15 18 4 0
-11 14 9 0
-6 -15 -2 0
5 -12 -15 0
-6 17 5 0
-13 5 -19 0
20 -1 14 0
9 -17 15 0
-5 19 -18 0
-12 8 -10 0
-18 14 -4 0
15 -9 13 0
9 -5 -1 0
10 -19 -14 0
20 9 4 0
-9 -2 19 0
-5 13 -17 0
2 -10 -18 0
-18 3 11 0
7 -9 17 0
-15 -6 -3 0
-2 3 -13 0
12 3 -2 0
-2 -3 17 0
20 -15 -16 0
-5 -17 -19 0
-20 -18 11 0
-9 1 -5 0
-19 9 17 0
12 -2 17 0
4 -16 -5 0
"""

# aim-50-1_6-yes1-1.cnf
AIM50_YES_CNF_CONTENT = """c FILE: aim-50-1_6-yes1-1.cnf
c
c SOURCE: Kazuo Iwama, Eiji Miyano (miyano@cscu.kyushu-u.ac.jp),
c          and Yuichi Asahiro
c
c DESCRIPTION: Artifical instances from generator by source.  Generators
c              and more information in sat/contributed/iwama.
c
c NOTE: Satisfiable
c
p cnf 50 80
5 28 41 0
5 -28 41 0
10 30 -41 0
5 -10 -41 0
-5 25 30 0
-5 -25 30 0
11 -30 -33 0
-11 -30 -33 0
7 -30 33 0
-7 14 33 0
-4 -7 -14 0
4 -14 -29 0
-1 -14 32 0
-1 4 -32 0
1 24 29 0
1 -24 -34 0
-6 -24 34 0
6 -24 38 0
6 -32 -38 0
32 44 48 0
-38 -44 48 0
22 29 -48 0
22 -29 32 0
-22 -25 -48 0
-22 25 40 0
18 -22 -40 0
-18 20 -40 0
-18 28 -40 0
-18 -28 39 0
-28 35 -39 0
-35 -39 43 0
-35 -43 -50 0
-43 -45 50 0
31 45 50 0
-31 -44 45 0
-15 44 49 0
-15 -31 -49 0
15 -31 36 0
15 23 -36 0
-23 -36 46 0
20 27 -46 0
-20 -23 27 0
-16 -27 -46 0
16 26 -27 0
16 17 -26 0
2 13 -17 0
2 -13 -26 0
-5 -17 -26 0
-2 -17 42 0
-2 12 -13 0
-2 -12 -42 0
8 13 -42 0
-8 -10 13 0
3 -8 10 0
-3 10 -37 0
-3 10 -47 0
10 19 47 0
-12 -19 47 0
12 -19 21 0
9 -19 -21 0
-9 -11 -21 0
-9 11 -49 0
11 41 49 0
19 -32 37 0
-1 39 -50 0
8 17 40 0
38 43 49 0
23 42 -47 0
-13 -29 37 0
-34 37 -47 0
-33 -37 50 0
-6 14 34 0
9 -20 -50 0
35 36 38 0
3 31 46 0
7 -16 21 0
-6 17 26 0
23 24 46 0
18 24 -45 0
-4 -6 7 0
"""

TEST_SUITE = {
    "uf20-01": UF20_01_CNF_CONTENT,
    "aim-50-yes": AIM50_YES_CNF_CONTENT,
}

def parse_dimacs_to_pysat(file_content: str) -> CNF:
    """Parses a DIMACS CNF string into a PySAT CNF object."""
    formula = CNF()
    for line in file_content.splitlines():
        line = line.strip()
        if line.startswith('c') or line.startswith('p') or not line:
            continue
        
        try:
            literals = [int(lit) for lit in line.split() if lit != '0']
            if literals:
                formula.append(literals)
        except ValueError:
            print(f"Skipping malformed line: {line}")
            
    return formula

def check_satisfiability(problem_name: str, cnf_content: str):
    """
    Uses PySAT to solve a CNF problem directly.
    """
    print(f"--- Checking: {problem_name} ---")
    
    try:
        # 1. Parse content into PySAT formula
        formula = parse_dimacs_to_pysat(cnf_content)
        print(f"  Parsed {formula.nv} variables and {len(formula.clauses)} clauses.")
        
        # 2. Initialize solver
        solver = Glucose3()
        solver.append_formula(formula)
        
        # 3. Solve
        print("  Solving...")
        start_time = time.time()
        is_sat = solver.solve()
        end_time = time.time()
        
        print(f"  Solver finished in {end_time - start_time:.4f} seconds.")
        
        # 4. Report result
        if is_sat:
            print(f"  ✅ RESULT: SATISFIABLE")
            model = solver.get_model()
            print(f"     Model (first 10): {model[:10]}...")
        else:
            print(f"  ❌ RESULT: UNSATISFIABLE")
            
        solver.delete()
        
    except Exception as e:
        print(f"  Error during PySAT check: {e}")
    
    print("-" * (len(problem_name) + 16))


if __name__ == "__main__":
    print("="*80)
    print("PySAT Sanity Check for SATLIB Benchmarks")
    print("="*80)
    
    for name, content in TEST_SUITE.items():
        check_satisfiability(name, content)
        print()
        
    print("="*80)
    print("Sanity check complete.")
    print("="*80)
