"""Can qlto_qml load an ARBITRARY dataset, and what does that cost? The QRAM question.

qlto_qml claims three circuits per epoch, flat in |D| and in M, and supplement
v123/v124 back that at tier A. But the claim is about CIRCUIT COUNT, and this
file asks the question that decides whether the module is usable on a real
dataset: what dataset can it actually hold?

WHAT THE CURRENT ENCODER CAN REPRESENT. qlto_qml._encode applies CRY(alpha[j,d])
to system qubit j controlled on register qubit d, so the angle vector for sample
x is

    ang_j(x) = sum_d alpha[j,d] * bit_d(x)

a LINEAR function of the register bits. The |D| = 2^d samples are therefore not
free: they are the 2^d vertices of a parallelepiped generated by the columns of
alpha, embedded in angle space. A real dataset is not a parallelepiped. So the
register as built is a structured-data device, not a data loader, unless the
encoder is changed.

WHAT CHANGING IT COSTS. An arbitrary angle table A[j, x] is loadable - it is a
uniformly controlled RY over ALL d register qubits, one per system qubit, which
is exactly the mux_ry qlto_qml already carries for state preparation. The
question is the price, and the price is the whole answer:

    linear encoder      n_sys * d          rotations  =  n_sys * log2|D|
    arbitrary encoder   n_sys * 2^d        rotations  =  n_sys * |D|

so CIRCUIT COUNT stays at three while GATE COUNT goes from logarithmic in |D| to
linear in it. That is the QRAM wall in its usual form, and this file measures
where it actually sits rather than asserting the exponent.

THE THREE THINGS MEASURED

  1. EXPRESSIVITY. Fit the linear encoder's alpha to a random target angle table
     by least squares and report the residual. If the linear form could represent
     arbitrary data the residual would be ~0 and there would be no problem to
     solve.
  2. CORRECTNESS of the arbitrary encoder - does the mux-loaded register actually
     produce the requested f_x for every sample?
  3. COST - gates, two-qubit gates and depth for both encoders as |D| grows, and
     whether cos and the three-circuit count survive the swap.

TIER (project rule R1): mixed and labelled per part. Part 1 is a least-squares
fit with NO CIRCUIT - it is a structural fact about what a linear map can
represent, which R1 permits, and it supports no cost or accuracy figure. Part 2
is tier B (Statevector, exact amplitudes) because it asks an exactness question -
does the encoder encode - and claims nothing about shots. Part 3 is tier A:
transpiled circuits and, for the cos column, AerSimulator with finite shots
through qlto_qml.QLTOQML itself.
"""
import contextlib
import io
import os
import sys

import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from qiskit import QuantumCircuit, QuantumRegister, transpile
from qiskit.circuit.library import efficient_su2
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator

from qlto_qml import QLTOQML, mux_ry, _cry

N_SYS = 3
SHOTS = 32768
BASIS = ['rz', 'sx', 'x', 'cx']


def _cos(a, b):
    na, nb = np.linalg.norm(a), np.linalg.norm(b)
    return float(np.dot(a, b) / (na * nb)) if na > 1e-12 and nb > 1e-12 else 0.0


def bits_matrix(d):
    """B[x, k] = bit k of x. The design matrix the linear encoder is stuck with."""
    return np.array([[(x >> k) & 1 for k in range(d)] for x in range(1 << d)],
                    dtype=float)


class ArbitraryQML(QLTOQML):
    """qlto_qml with the linear encoder replaced by a per-sample angle table.

    angles[j, x] is the rotation applied to system qubit j for sample x, with no
    constraint relating different x. Everything else - the weighted register, the
    two sign branches, the V6 gradient - is inherited unchanged, which is the
    point: only the encoder differs.
    """

    def __init__(self, core, angles, y, **kw):
        angles = np.asarray(angles, float)
        n_sys, S = angles.shape
        d = int(np.log2(S))
        if 1 << d != S:
            raise ValueError("angle table has %d columns, not a power of two" % S)
        # the base class reads alpha.shape for (n_sys, n_data); hand it a dummy
        # of the right shape and override every use of its VALUES below
        super().__init__(core, np.zeros((n_sys, d)), y, **kw)
        self.angles = angles

    def _encode(self, qc, dq, sq):
        for j in range(self.n_sys):
            mux_ry(qc, self.angles[j], [dq[k] for k in range(self.n_data)], sq[j])

    def f_exact(self, x, theta):
        qc = QuantumCircuit(self.n_sys)
        for j in range(self.n_sys):
            qc.ry(float(self.angles[j, x]), j)
        qc.compose(self.core.assign_parameters(np.asarray(theta, float)),
                   inplace=True)
        return float(np.real(Statevector(qc).expectation_value(self.O_sys)))


print("=" * 100)
print("v125  ARBITRARY DATA IN THE REGISTER:  what qlto_qml can hold, and the price")
print("=" * 100)
print("  qlto_qml's three circuits are flat in |D|. This asks what DATASET fits")
print("  in the register at all, which is the question that decides application.")
print()

# ------------------------------------------------------------------ PART 1
print("-" * 100)
print("PART 1  what can the linear encoder represent?   NO CIRCUIT (tier C)")
print("-" * 100)
print("  ang_j(x) = sum_d alpha[j,d]*bit_d(x) is linear in the register bits, so")
print("  the reachable angle tables form a d-dimensional subspace of R^(2^d).")
print("  Least-squares fit of alpha to a random target table, per sample size:")
print()
print("      d   |D|   free params   rel. residual   variance captured")
print("   " + "-" * 68)
rng = np.random.default_rng(3)
for d in (2, 3, 4, 5):
    S = 1 << d
    B = bits_matrix(d)
    tgt = rng.uniform(-np.pi, np.pi, (N_SYS, S))
    alpha, *_ = np.linalg.lstsq(B, tgt.T, rcond=None)
    resid = tgt.T - B @ alpha
    rel = float(np.linalg.norm(resid) / np.linalg.norm(tgt))
    print("   %4d  %4d      %4d          %.4f          %5.1f%%"
          % (d, S, N_SYS * d, rel, 100 * (1 - rel ** 2)))
print()
print("  The linear encoder holds n_sys*d numbers and an arbitrary table needs")
print("  n_sys*2^d, so the residual grows with d and the register is a")
print("  STRUCTURED-DATA device as built. It cannot load a general dataset.")
print()

# ------------------------------------------------------------------ PART 2
print("-" * 100)
print("PART 2  does the mux encoder actually load an arbitrary table?   tier B")
print("-" * 100)
print("  Exact amplitudes. Compare f_x read out of the register circuit against")
print("  f_x from directly preparing sample x's angles. Exactness question, so")
print("  no shots and no cost figure here.")
print()
print("      d   |D|   max |f_reg - f_direct|   verdict")
print("   " + "-" * 60)
ok2 = True
for d in (2, 3, 4):
    S = 1 << d
    angles = rng.uniform(-np.pi, np.pi, (N_SYS, S))
    core = efficient_su2(N_SYS, reps=1)
    theta = rng.uniform(-np.pi, np.pi, core.num_parameters)
    q = ArbitraryQML(core, angles, np.zeros(S), shot_budget=SHOTS, sim_seed=1)

    # read every f_x out of ONE register circuit, exactly, by conditioning the
    # joint statevector on the register outcome
    dq = QuantumRegister(d, 'd'); sq = QuantumRegister(N_SYS, 's')
    qc = QuantumCircuit(dq, sq)
    from qlto_qml import prep_weights
    prep_weights(qc, np.ones(S) / S, dq)
    q._encode(qc, dq, sq)
    qc.compose(core.assign_parameters(theta), qubits=list(sq), inplace=True)
    psi = Statevector(qc).data.reshape([2] * (N_SYS + d))

    worst = 0.0
    for x in range(S):
        idx = [slice(None)] * (N_SYS + d)
        for k in range(d):                      # register qubit k is axis -(k+1)
            idx[-(k + 1)] = (x >> k) & 1
        blk = np.asarray(psi[tuple(idx)]).ravel()
        nrm = np.vdot(blk, blk).real
        # system qubit 0 is the LAST axis of the remaining block
        sub = blk.reshape([2] * N_SYS)
        p0 = float(np.sum(np.abs(sub[..., 0]) ** 2))
        p1 = float(np.sum(np.abs(sub[..., 1]) ** 2))
        f_reg = (p0 - p1) / max(nrm, 1e-300)
        worst = max(worst, abs(f_reg - q.f_exact(x, theta)))
    ok2 &= worst < 1e-9
    print("   %4d  %4d          %.2e            %s"
          % (d, S, worst, "ok" if worst < 1e-9 else "FAIL"))
print()
if not ok2:
    print("   FAIL - the arbitrary encoder does not encode; PART 3 would be noise.")
    sys.exit(1)
print("   PASS - an arbitrary dataset IS loadable. The rest is what it costs.")
print()

# ------------------------------------------------------------------ PART 3
print("-" * 100)
print("PART 3  the price, on transpiled circuits   tier A")
print("-" * 100)
print("  Transpiled to %s. 'circuits' is counted from q.ncircuits, not asserted."
      % BASIS)
print()
print("      d   |D|    encoder     gates    2q gates   depth   circuits   cos")
print("   " + "-" * 84)
be = AerSimulator(seed_simulator=5)
cost = {}
for d in (2, 3, 4, 5):
    S = 1 << d
    core = efficient_su2(N_SYS, reps=1)
    theta = rng.uniform(-np.pi, np.pi, core.num_parameters)
    y = rng.integers(0, 2, S) * 2.0 - 1.0
    tgt = rng.uniform(-np.pi, np.pi, (N_SYS, S))
    B = bits_matrix(d)
    alpha_fit, *_ = np.linalg.lstsq(B, tgt.T, rcond=None)

    for tag in ('linear', 'arbitrary'):
        if tag == 'linear':
            q = QLTOQML(core, alpha_fit.T, y, shot_budget=SHOTS, sim_seed=5,
                        backend=be)
        else:
            q = ArbitraryQML(core, tgt, y, shot_budget=SHOTS, sim_seed=5,
                             backend=be)
        qc = q.batched(np.ones(S) / S)
        t = transpile(qc.assign_parameters(theta), basis_gates=BASIS,
                      optimization_level=1)
        ops = t.count_ops()
        g2 = ops.get('cx', 0)
        c0 = q.ncircuits
        with contextlib.redirect_stdout(io.StringIO()):
            f, _den = q.f_hat(theta)
            g_est, _ = q.gradient(theta, w=f - y)
        g_true, _ = q.grad_exact(theta)
        cost[(d, tag)] = (sum(ops.values()), g2, t.depth())
        print("   %4d  %4d   %-10s  %5d      %5d    %5d      %2d      %+.4f"
              % (d, S, tag, sum(ops.values()), g2, t.depth(),
                 q.ncircuits - c0, _cos(g_est, g_true)))
    print()

# slopes of the whole-circuit counts from PART 3; PART 4 needs them to say what
# it is correcting, and READING IT reuses them
xs = np.array([2, 3, 4, 5], float)
sa = float(np.polyfit(xs, np.log2([cost[(d, 'arbitrary')][1]
                                   for d in (2, 3, 4, 5)]), 1)[0])
sl = float(np.polyfit(xs, np.log2([max(cost[(d, 'linear')][1], 1)
                                   for d in (2, 3, 4, 5)]), 1)[0])

# ------------------------------------------------------------------ PART 4
print("-" * 100)
print("PART 4  WHICH BLOCK IS THE COST?  prep vs encode, counted separately")
print("-" * 100)
print("  PART 3's 'linear' column fits a slope of %.2f in d, which is NOT the" % sl)
print("  n_sys*d the linear encoder should cost. Something else in the circuit is")
print("  growing with |D|, so the two blocks are counted apart here rather than")
print("  attributed by argument.")
print()
print("      d   |D|   prep 2q   linear enc 2q   arbitrary enc 2q   prep share")
print("   " + "-" * 78)
from qlto_qml import prep_weights
split = {}
for d in (2, 3, 4, 5):
    S = 1 << d
    tgt = rng.uniform(-np.pi, np.pi, (N_SYS, S))
    B = bits_matrix(d)
    alpha_fit, *_ = np.linalg.lstsq(B, tgt.T, rcond=None)

    dq = QuantumRegister(d, 'd')
    qp = QuantumCircuit(dq)
    prep_weights(qp, rng.dirichlet(np.ones(S)), dq)   # a REAL weight vector
    n_prep = transpile(qp, basis_gates=BASIS,
                       optimization_level=1).count_ops().get('cx', 0)

    dq = QuantumRegister(d, 'd'); sq = QuantumRegister(N_SYS, 's')
    qe = QuantumCircuit(dq, sq)
    for j in range(N_SYS):
        for k in range(d):
            _cry(qe, float(alpha_fit.T[j, k]), dq[k], sq[j])
    n_lin = transpile(qe, basis_gates=BASIS,
                      optimization_level=1).count_ops().get('cx', 0)

    qe = QuantumCircuit(dq, sq)
    for j in range(N_SYS):
        mux_ry(qe, tgt[j], [dq[k] for k in range(d)], sq[j])
    n_arb = transpile(qe, basis_gates=BASIS,
                      optimization_level=1).count_ops().get('cx', 0)

    split[d] = (n_prep, n_lin, n_arb)
    print("   %4d  %4d    %5d       %7d          %9d        %5.1f%%"
          % (d, S, n_prep, n_lin, n_arb,
             100.0 * n_prep / max(n_prep + n_lin, 1)))
print()
sp = float(np.polyfit(xs, np.log2([max(split[d][0], 1) for d in (2, 3, 4, 5)]), 1)[0])
se = float(np.polyfit(xs, np.log2([max(split[d][1], 1) for d in (2, 3, 4, 5)]), 1)[0])
print("  Fitted slope of log2(2q gates) against d:")
print("      weighted state prep   %.2f   -> ~ |D|^%.2f" % (sp, sp))
print("      linear encoder        %.2f   -> ~ |D|^%.2f" % (se, se))
print()

print("=" * 100)
print("READING IT")
print("=" * 100)
print("  CIRCUIT COUNT IS UNCHANGED at three for both encoders at every size -")
print("  the flat-in-|D| claim in qlto_qml survives arbitrary data intact.")
print()
print("  GATE COUNT DOES NOT. Two-qubit gates, arbitrary over linear:")
print()
print("      |D|     linear 2q    arbitrary 2q    ratio")
print("   " + "-" * 56)
for d in (2, 3, 4, 5):
    a, b = cost[(d, 'linear')][1], cost[(d, 'arbitrary')][1]
    print("   %6d      %6d        %8d       %5.1fx" % (1 << d, a, b, b / max(a, 1)))
print()
print("  Fitted slope of log2(WHOLE-CIRCUIT 2q gates) against d = log2|D|:")
print("      with linear encoder     %.2f" % sl)
print("      with arbitrary encoder  %.2f" % sa)
print()
print("  Both are near or above 1.0, so the FULL circuit is linear in |D| either")
print("  way - even with the cheap encoder.")
print()
print("  AND THE ENCODER WAS THE WRONG SUSPECT FOR IT. PART 4 counts the blocks")
print("  apart: the linear encoder scales as |D|^%.2f, logarithmic as designed," % se)
print("  while THE WEIGHTED STATE PREP scales as |D|^%.2f and reaches %.0f%% of the"
      % (sp, 100.0 * split[5][0] / max(split[5][0] + split[5][1], 1)))
print("  two-qubit gates by |D|=32, still climbing. Reading PART 3's %.2f as" % sl)
print("  'the linear encoder is cheap' would have been wrong in a specific way:")
print("  the encoder IS cheap, and the circuit is not.")
print()
print("  THAT CANNOT BE FIXED BY CHOOSING A BETTER DATASET. qlto_qml's premise is")
print("  p_x proportional to |w_x| - an ARBITRARY distribution that changes every")
print("  epoch. Setting 2^d - 1 free amplitudes needs at least 2^d - 1 angles, so")
print("  the prep is Theta(|D|) by parameter counting, not by any weakness of the")
print("  Gray-code construction. The weighted register is inherently linear in |D|")
print("  in GATES however structured the data is. Structure buys the encoder; it")
print("  does not buy the prep.")
print()
print("  Loading 1024 arbitrary samples extrapolates to ~%d two-qubit gates by the"
      % int(2 ** (sa * 10) * cost[(2, 'arbitrary')][1] / 2 ** (sa * 2)))
print("  arbitrary-encoder fit, which no NISQ device runs. That is the QRAM wall;")
print("  this file locates it rather than moving it.")
print()
print("  ON THE DATASET RESTRICTION ITSELF. PART 1 shows the linear encoder")
print("  captures only a d-dimensional subspace of a 2^d-dimensional angle table -")
print("  40%, 45%, 26%, 12% of the variance of a random target at d = 2..5, falling")
print("  as d grows. So it is a STRUCTURED-DATA device: it fits samples generated")
print("  by a few underlying factors - parameter sweeps, designed experiments,")
print("  lattices of settings - and not unstructured data. That restriction is real")
print("  and is separate from the gate-count question PART 4 takes up.")
print()
print("  SO WHAT IS THE MODULE ACTUALLY FOR, given both findings. Three circuits")
print("  per epoch against parameter-shift's 2M|D| is a real and large saving in")
print("  CIRCUIT COUNT - the quantity that carries per-job latency, queue time and")
print("  compilation overhead on real hardware. It is not a saving in depth, and")
print("  the Theta(|D|) prep means |D| is bounded by coherence, not by the method.")
print("  The regime where that trade is favourable is: modest |D| (tens), a system")
print("  register small enough that the prep fits in coherence, structured samples")
print("  so the cheap encoder suffices, and a workload where job count rather than")
print("  circuit depth is the binding constraint. Sweeps and designed experiments")
print("  sit in that regime. Unstructured large-batch learning does not.")
print()
print("  SCOPE. N_sys=%d, |D| <= 32, efficient_su2 reps=1, %d shots, one seed per"
      % (N_SYS, SHOTS))
print("  cell, no noise model, no hardware, single-Pauli readout so G=1. The")
print("  slope fits use four points over one decade and are trends, not laws. No")
print("  claim here about whether a NOISY device preserves the cos column - that")
print("  is untested for this module and is the gap that most limits application.")
