/-
  TFIM.lean: Transverse Field Ising Model (BQP Solvable Benchmark)

  The TFIM is a canonical example of an "easy" quantum system (solvable in P).
  H = -J ∑ Z_i Z_{i+1} - h ∑ X_i

  It maps to free fermions via the Jordan-Wigner transformation.
  Theory predicts its DLA is isomorphic to so(2n), with dimension n(2n-1).
-/

import BQP_NP.Basic.LieAlgebra
import BQP_NP.Basic.PauliOperators
import Mathlib.Algebra.Lie.Subalgebra

open Matrix Complex

namespace TFIM

variable (n : ℕ)

/-- Pauli-X on qubit i (I elsewhere) -/
def pauliX (i : Fin n) : PauliString n :=
  fun k => if k = i then Pauli.X else Pauli.I

/-- Pauli-Z on qubits i and i+1 (I elsewhere) -/
def pauliZZ (i : Fin n) (h_next : i.val + 1 < n) : PauliString n :=
  fun k =>
    if k = i then Pauli.Z
    else if k.val = i.val + 1 then Pauli.Z
    else Pauli.I

/-- Construct the TFIM Hamiltonian matrix -/
noncomputable def matrix (J h : ℝ) : Matrix (Fin (2^n)) (Fin (2^n)) ℂ :=
  let termZ := (List.finRange n).foldl
    (fun M i =>
      if h_next : i.val + 1 < n then
        M + (-J : ℂ) • (pauliZZ n i h_next).toMatrix
      else
        M)
    0
  let termX := (List.finRange n).foldl
    (fun M i =>
      M + (-h : ℂ) • (pauliX n i).toMatrix)
    0
  termZ + termX

/-- The TFIM Hamiltonian as a Hamiltonian structure -/
noncomputable def hamiltonian (J h : ℝ) : Hamiltonian n where
  mat := matrix n J h
  hermitian := by
    -- Proof sketch: sum of Real-coefficient Pauli matrices is Hermitian
    -- Pauli matrices are Hermitian.
    -- Real scalar multiplication preserves Hermiticity.
    -- Sum preserves Hermiticity.
    sorry

/-- The DLA generated by TFIM (Hamiltonian + X_all mixer) -/
noncomputable def dla (J h : ℝ) : LieSubalgebra ℂ (Matrix (Fin (2^n)) (Fin (2^n)) ℂ) :=
  let H := hamiltonian n J h
  -- Standard mixer H_mixer = ∑ X_i matches the field term, usually ok
  let H_mixer := hamiltonian n 0 1 -- Just the X terms
  DLA H H_mixer

/-- THEOREM (Year 1 Goal): TFIM DLA dimension is quadratic.
    This formally establishes one side of the BQP vs NP gap.

    Proof sketch:
    1. TFIM generators map to quadratic operators in Majorana fermions c_i
    2. Quadratic Majoranas span the Lie algebra so(2n)
    3. dim(so(2n)) = n(2n-1) = 2n^2 - n

    For now, axiomatized as "known physics". -/
axiom tfim_dla_dimension_bound (J h : ℝ) (h_nonzero : h ≠ 0) :
    Module.finrank ℂ (dla n J h) ≤ 2 * n^2 + n

end TFIM
